async function main() {
	/*
	 * Retrieve accounts provided by our local Hardhat environment.
	 * The "other accounts" are automatically generated by Hardhat.
	 */
	const [owner, otherAccount] = await ethers.getSigners();
	const D42 = await ethers.getContractFactory("d42");
	const d42 = await D42.deploy(ethers.utils.parseEther("1000"));
	await d42.deployed();

	console.log("Deployed by:", owner.address);
	console.log("Other account:", otherAccount.address);

	// Try minting from otherAccount
	try {
		const d42Connected = d42.connect(otherAccount);
		await d42Connected.mint(otherAccount.address, ethers.utils.parseEther("100"));
	} catch (error) {
		console.error("Minting failed from non-owner account as expected:");
		console.error(error.message);
	}
}

main();
